import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Opciones = [
  "inicio",
  "laboratorio",
  "Contactanos",
  "Inventario",
  "Mis solicitudes",
  "configuracion",
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#1E1C27]">{children}</body>
    </html>
  );
}

type Props = {};
