import "./globals.css";
import Image from "next/image";
import { AiFillHome } from "react-icons/ai";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Opciones = [
  "inicio",
  "laboratorio",
  "Contactanos",
  "Inventario",
  "Mis solicitudes",
  "configuracion",
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#1E1C27]">
        <div className="flex">
          <div className="w-1/5 h-screen flex flex-col align-center p-4">
            {/* sidebar */}
            <img
              src={
                "https://th.bing.com/th/id/R.0e4d95a788b68565e74fc9b2e65efa0a?rik=a7CYTmm6j6%2f7pA&pid=ImgRaw&r=0"
              }
            />
            <div className="flex flex-col gap-6 mt-10">
              {Opciones.map((opcion) => {
                return <BarOptions />;
              })}
            </div>
            <div className="text-white flex flex-col"></div>
          </div>
          <div className="w-full rounded-2xl border-2 bg-[#F5F5F5]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}

type Props = {};

const BarOptions = (Props: Props) => {
  return (
    <button className="text-white hover:bg-[#45444D] p-2 rounded-lg flex items-center gap-4">
      <AiFillHome className="w-6 h-6" />
      <label className="text-[20px]">Laboratorio</label>
    </button>
  );
};
