import Image from "next/image";
import { AiFillHome } from "react-icons/ai";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Opciones = [
  "inicio",
  "laboratorio",
  "Contactanos",
  "Inventario",
  "Mis solicitudes",
  "configuracion",
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex">
      <div className="w-[330px] h-screen flex flex-col align-center p-4">
        {/* sidebar */}
        <img
          src={
            "https://th.bing.com/th/id/R.0e4d95a788b68565e74fc9b2e65efa0a?rik=a7CYTmm6j6%2f7pA&pid=ImgRaw&r=0"
          }
        />
        <div className="flex flex-col gap-2 mt-10">
          {Opciones.map((opcion) => {
            return <BarOptions />;
          })}
        </div>
        <div className="text-white flex flex-col"></div>
      </div>
      <div className="w-full rounded-2xl border-2 bg-[#F5F5F5]">{children}</div>
    </div>
  );
}

type Props = {};

const BarOptions = (Props: Props) => {
  return (
    <div className="text-white hover:bg-[#45444D] px-3 rounded-lg flex items-center gap-2 cursor-pointer duration-[200ms] flex-shrink-0 min-w-[34px] h-[34px]">
      <AiFillHome className="w-5 h-5" />
      <label className="text-[14px] cursor-pointer">Laboratorio</label>
    </div>
  );
};
